language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "codemore-test";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: Z3G2mvEhVA2qUaESTBYCA52IWRhpp7eEEELRk+GgYYvoWdob4ByTCft7C+HVj/ie6+C+J+BEOvlwUu1Ba+7aNxWYfEwzEoEVm27EaGgAMvrhImNB2vWofYgNzGtK3zEkRfl8C0mKBA2Xtp/6xukW/EjfS7H7Z1mVYtZHgTD6xcvQQ4uNBZnp8sp2WT6GXxA1BvRIIz+MkCLdGukKLnKkH/2BjCwK10Y0uHhjqANi5iw7R8p5ZHyOppk/Nlmd/FcCAIqXflCo3x3IIWFOfnfRhx1P44okBzJNIhLYwCXXq+muAA60M5bXJXWXFbjGEkVbZSJtgEiWhU0nZHEN0eh93Le3zANocx1J+CrvbO4WnxCCnVz7TR4u9gdkZE2xD3wh0y4125VIaMIxv47lfRMuJysQxI3/PHOHMLIYnUe7AfcN/F4E7Fg6yYyhIJ1yI0FPHr3YhNgr5pRedxc+yV20X7P65gk1uV1Amvcfkas7imbYu3R8AMaoK8DHKQko679GrlWWk2gJp1O4HmmuBNSE1EAmYvYI3C9+P7k4+nzTN4ZvRBLcGgjatgPEjo0LoCmOj+XI6Jhs+plKTE/uaTtYFNhqMZ3BNp/aNIeoDXqkuTEEe09CD8qLxyzcGBj+qam2rZRgfMD1Lqfhdqa6DB4rLwSvVtnxvCvZbbRFDSFaVQc=
  app: codemore
  on:
    repo: yeoldecodemore/CodeMore
