language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "codemore-test";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: i+hlw8XnJhBI5tiEo/KNT/Y8a8HdCcUgL0rPJ1DQg8qB8qUI58aUPjw9ucwzKBh2IIrnLiCF1HsxeScJxoHVXOB7vqZcjWSre3crEnLNjzcFWoiP+UWnzXtctzTOdlEQ9Wu2knXbazXlbKBx0Phi5fyLQb89VYE7Y+RdbbrTyJLPBWiU7SW/4P9QFRpTG0sUzavDkVW8h1fepG2aw1kpC+WXYGonIdqcMNNcXcqTL8cOVuDWECGW5WATV6yZuOL1n4ynzHHhzFZub2WgR64zrFsmNjzmHhUlTiSjvIvJhOMk3iVOLrXO6mQoUGFHhsbnRmv0b9UJsQs/zOB+S4P4OWqDAaksFdE9xlOvOiBL8l9fJuU6wHONnKgLYKrygTC1m4oaGb+V0c7lLGstFN5QjL3/wJ5mm9emTT/fAdps5UG78zD8rAtRvD+KlA3kIJ9+Jj6LCbp7I5hDNDwI5uBWS1Czwe6XfPEQ5KpS9qjbmdQR+lg61SUJoaMiJTFueksN5ocUmp1GLu1ePZCXayq1h6K7Uu6QGLiXSshzsxpZw801/UB/QksvNWHITUcmvrEgCTKscdlsLf7F3wXPA+CcXlZc6bI1lkuQYmIuVasq051XhciDXyCEqg9zNAOORKEaQX1iFo4rHH06LQ9mMiorCei9A9aeYo4E9+qpFBipP2E=
  app: CodeMore
  on:
    repo: yeoldecodemore/CodeMore
