language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "codemore-test";' -U postgres
script:
- npm test
- npm run build-client
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: codemore
  api_key:
    secure: VWEEaWMQ/RCpTwwrigKCm3tnjSWTTI+gfqSQDN4r/wq7Vzys1FqAfSSbPvCu79H1IkePd69UvejmNW80dKrK5RlFziL3raGQf1OxMV7PtzKC3uRqZkAQwdSPP5B5uTllHu+wCwGk3nTy9G2hQORcrAST3gcSw2J/YHFXM2BKCWGZda5YGT7rEajxoCslYNcuBXGG6ilKQRqnrq/+ZucxWzKcPCLT5oyf4LCWu54oFngl7vtSKNA5dWEIv5nc/i+Q1x/6wPL4d0sSEQaz62QiQ7EuYHV2pbB1v6KAchKsPODGrZzqleBcAbdYdpP/gQn9yCMYxydxcqCgRkVNC6AdZVvU9LPb+uMZXc8SKxVNpZwwMR4ihrmOwtH8yXqJjP9d6UHyZcD+DTiDs4faU2Bbi/9txgPdSzbkMaM5gPt8R1iXwAggGtZ6YJETsP4kmcAR6CGauFLuJiExFjNpYuZ9LXQ0EWZAEihGxpeqGhvN4iTL53NIPDxA0WduBvnFA5YNBV+T0NWyoTbIQsthfzBRQA4WKtVoDzaVj/tsVluLBs36xAtJXvDEZhXPzlkIXesfCisR+TjANlXRrtDA6TRzHMOp9NRFcrfzGaeafRpwhxcERvdGZDz+W5bAsbX1wdElipFQ+AzFZnnyZzYmsHTuipcT5wRUQTa4uiZvno6a1ak=
