language: node_js
node_js:
  - node
services:
  - postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
  - npm ci
before_script:
  - psql -c 'create database "codemore-test";' -U postgres
script:
  - npm test
  - npm run build-client
before_deploy:
  - rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: Rl8s+JWyHPaL4pmQnTV1RvOg1uds4oLzs8SNLefUaHsHSZYzxRVr18q2HHo3q5RM5xYYT7pa3CvFCjvxVlGVYdnVIgI76v46ptxNAeeIyY4vdac0u4rwJ+5yfAYQnuceIr2rqR9O4P/XMCuhzj5T6fqsZP6N1M3zukbvGjfxlu4X4M/4o9df4nXK2wrX1BBp2c2SEyeQyLtHf0BkEcBlivDp3NCU/K8VevF/kd1rZwB2FSDaeImkV2m8k6Mr/nBZqL3EjVKTDjf+ysSnK5oCP1j2WETBtCIgHdJ+Wtx1gSnDp1yVgUwHco09PaH+Bs2tVdY1OFQbzevldDAkyn2d+dOY+0yG5GU/2WjI4wWM2EnsOQ+hDUSAvpJJAIlywGV8KL0shC3Z2hJlaYvdQQ+zeIsH0prCrblXA5m0J1mMXRbeJHbuJCk4eBesC/k00QcKiMnVFa6LBD6S78uuIUxBBLrn+QnqkKTOBNZw9lQeYDNwjRqLAddjidejYOHhSYpAafHUJQ9Yljdz52LcuCavOdhb28oq96zbtb0Gy3PkAadR9tANjZiMXm1gLdsmtNGm4ebxb0OVCP0Mm8Zktdkasy355nzL1VfejZLtvzcu36/fMNMlbJwVVm2E5mAlDGMIq2OhwSJfZKQkoaMmHRHGgzuwC3pQyXDB45iU50EITzY=
  app: codemore
  on:
    repo: yeoldecodemore/CodeMore
